### ISSUE TITLE
Regarding JOSS submission #6339 EllipticForest 

### ISSUE THREAD

**Issue by sandeshkatakam** [DamynChipman/EllipticForest#7]
I am reviewing this software paper on JOSS Reviews. I would like to know if there is a documentation page for the software or even README files that describes the installation and reference to the core functionality of the package

**Comment by DamynChipman** [comment]
Yes, the README at the root of the repo has example usage and installation instructions. The `examples` directory has a variety of use cases, each with a README that shows basic use.

**Comment by sandeshkatakam** [comment]
Okay, I will check it out. Thank you
