### ISSUE TITLE
joss paper example

### ISSUE THREAD

**Issue by lukeolson** [DamynChipman/EllipticForest#9]
https://github.com/openjournals/joss-reviews/issues/6339

I see that the JOSS paper references an elliptic polar star example: `examples/elliptic-single/output_polar_star.png`.  Is there a way to reproduce this result in `examples`?  `v1-joss-paper` does not seem to have this in `examples/elliptic-single` but I may be missing something...

**Comment by DamynChipman** [comment]
Ah, you're right. The polar-star example can be found in the main branch, at `examples/papers/p1-serial/poisson-2.cpp` (https://github.com/DamynChipman/EllipticForest/blob/main/examples/papers/p1-serial/poisson-2.cpp). It's an example of a Poisson equation with a highly local RHS function. The `v1-joss-paper` branch `elliptic-single` example is set up to solve the Poisson equation for $u(x,y) = \sin(x) + \sin(y)$. I put the polar star example in the paper as it highlights the adaptive mesh better than the sine problem.

You can run the examples in `examples/papers/p1-serial` to reproduce those results. They correspond to the examples ran for a different paper, but they should work in parallel regardless.

Alternatively, I could either change the picture in the paper to match the example in `elliptic-single` or change the problem solved in `elliptic-single` to be the polar star problem. Any suggestions?

**Comment by DamynChipman** [comment]
I went ahead and put the sine/cosine problem in the paper as it better corresponds to the current example in `examples/elliptic-single`. You can reproduce that example by following the instructions in the README: https://github.com/DamynChipman/EllipticForest/tree/v1-joss-paper/examples/elliptic-single. Each of the examples have a corresponding README with details about the example and how to run it.

The polar-star problem is also still available if you want to reproduce that in the directory I mentioned above.

**Comment by lukeolson** [comment]
@DamynChipman looks good!
